### ISSUE TITLE
doesn't handle all imports 

### ISSUE THREAD

**Issue by bitsofinfo** [NilsCoding/mvn-download-wsdl#1]
these are not being imported (i.e. imports within other imported xsds)
```
<xs:import schemaLocation="https://wartest.mydomain.com/Services/Apples/Apples Service.svc?xsd=xsd2"
           namespace="http://mydomain.com/ABC/WebService/CB/Apple/Entities"/>
```

nor are these kinds

```
    <wsdl:import location="https://mydomain.com/whatever?wsdl"
                 namespace="http://tempuri.org/"/>
```

**Comment by NilsCoding** [comment]
Thank you for your feedback.

My main use case for the current implementation is to handle JAX-WS auto-generated WSDL and Schemas, and I've never encountered nested schema imports there, so they're currently not supported during processing. And neither are WSDL imports in WSDLs because they have been out of scope yet, too.

I was recently able to construct a webservice with auto-generated nested schema imports and I'm working on the improvements to handle this kind of data.

**Comment by NilsCoding** [comment]
Schema imports (resulting in downloading and locally storing referenced schema files) are supported since version 1.2.0
However, I have currently no plans to also support WSDL imports, but I will split that topic into a separate issue.
